project:
  type: website
  resources:
    - "images/twitter-card.png"
    - "materials"
  render:
    - "*.qmd"
    - "!materials"
    - "!README.Rmd"
  pre-render: zip.R

website:
  page-navigation: true
  title: "Shiny web applications"
  description: "Homepage for WOMBAT 2024 Shiny workshop"
  site-url: "https://workshop.nectric.com.au/shiny-wombat24"
  
  repo-url: https://github.com/mitchelloharawild/workshop-shiny-wombat24
  repo-actions: [edit, issue]

  # opengraph: true
  twitter-card:
    creator: "@mitchoharawild"
    image: "/images/twitter-card.png"

  favicon: "/images/shiny.svg"

  page-footer:
    left: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    right: "&copy; Copyright 2024, Nectric Pty Ltd."
    background: "#60A2DF"

  navbar:
    background: "#60A2DF"
    logo: "images/shiny.svg"
    pinned: true
    align: center
    right:
      - icon: download
        text: Downloads
        menu: 
          - text: Everything! Including this website!
            href: 'https://github.com/mitchelloharawild/workshop-shiny-wombat24/archive/refs/heads/main.zip'
          - text: Course Materials
            href: 'slides.zip'
          - text: Shiny Applications
            href: 'apps.zip'
      - icon: file-certificate
        href: license.qmd
      - icon: github
        href: https://github.com/mitchelloharawild/workshop-shiny-wombat24
    left:
      - text: Sessions
        menu: 
          - text: Basics of Shiny
            href: sessions/01_basics.qmd
          - text: Reactive programming
            href: sessions/02_reactive.qmd
          - text: Publishing apps
            href: sessions/03_publish.qmd
      - href: schedule.qmd

from: markdown+emoji

format:
  html:
    theme:
      light: [cosmo, theme.scss]
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Noto Sans, Helvetica, sans-serif"
    include-after-body: plausible.html
